Backend: Vivado
ClockPeriod: 10
HLSConfig:
  LayerName:
    batch_normalization:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 4096
      Trace: true
    batch_normalization_1:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 4096
      Trace: true
    batch_normalization_2:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 4096
      Trace: true
    batch_normalization_3:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 4096
      Trace: true
    batch_normalization_4:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 4096
      Trace: true
    input_1:
      Precision: ap_fixed<8,8>
      ReuseFactor: 4096
      Trace: true
    q_activation:
      Precision:
        result: ap_fixed<7,4>
      ReuseFactor: 4096
      Trace: true
    q_activation_1:
      Precision:
        result: ap_fixed<5,3>
      ReuseFactor: 4096
      Trace: true
    q_activation_2:
      Precision:
        result: ap_fixed<6,4>
      ReuseFactor: 4096
      Trace: true
    q_activation_3:
      Precision:
        result: ap_fixed<6,4>
      ReuseFactor: 4096
      Trace: true
    q_activation_4:
      Precision:
        result: ap_fixed<5,3>
      ReuseFactor: 4096
      Trace: true
    q_dense:
      Precision:
        bias: ap_fixed<5,1>
        weight: ap_fixed<6,1>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_1:
      Precision:
        bias: ap_fixed<9,4>
        weight: ap_fixed<6,1>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_2:
      Precision:
        bias: ap_fixed<8,1>
        weight: ap_fixed<8,1>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_3:
      Precision:
        bias: ap_fixed<7,1>
        weight: ap_fixed<3,2>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_4:
      Precision:
        bias: ap_fixed<6,1>
        weight: ap_fixed<6,1>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
    q_dense_5:
      Precision:
        bias: ap_fixed<9,4>
        weight: ap_fixed<5,1>
      ReuseFactor: 4096
      Trace: true
      accum_t: ap_fixed<32,16>
  Model:
    Precision: ap_fixed<32,16>
    ReuseFactor: 4096
    Strategy: Resource
IOType: io_parallel
#KerasModel: !keras_model 'hls/autoq_model_downsampled/train_config_bits_8_frames_5_mels_128_encDims_8_hidDims_64_halfcode_2_fan_64_bn_True_qbatch_False_l1reg_0/pynqz2_anomaly_detector_m_axi_8_serial_prj/keras_model.h5'
OutputDir: hls/autoq_model_downsampled/train_config_bits_8_frames_5_mels_128_encDims_8_hidDims_64_halfcode_2_fan_64_bn_True_qbatch_False_l1reg_0/pynqz2_anomaly_detector_m_axi_8_serial_prj
ProjectName: anomaly_detector
Stamp: b6C78840
XilinxPart: xc7z020clg400-1
